name: Deploy to EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Create .env File from Secret
      - name: Create .env File
        env:
          ENV_STAGING: ${{ secrets.ENV_STAGING }}
        run: |
          echo "$ENV_STAGING" > .env

      # Step 4: Build the project
      - name: Build with Maven
        run: mvn clean install

      # Step 5: Copy jar file to EC2
      - name: Deploy JAR to EC2
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          EC2_HOST: ${{ secrets.SSH_HOST_DEV }}
          EC2_USER: ${{ secrets.SSH_USER }}
        run: |
          echo "${SSH_KEY}" > key.pem
          chmod 600 key.pem
          scp -i key.pem target/spring-boot-security-postgresql-0.0.1-SNAPSHOT.jar ${EC2_USER}@${EC2_HOST}:~/sy/sy.jar

      # Step 6: Restart the application on EC2
      - name: Restart Application
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          EC2_HOST: ${{ secrets.SSH_HOST_DEV }}
          EC2_USER: ${{ secrets.SSH_USER }}
        run: |
          ssh -i key.pem ${EC2_USER}@${EC2_HOST} << 'EOF'
          cd ~/sy
          PID=$(sudo lsof -ti:8080 || echo "")
          if [ -n "$PID" ]; then
            sudo kill -9 $PID
          fi
          nohup java -jar ./sy.jar > test.log 2>&1 &
          echo "Deployment Complete"
          EOF
